[env]
txPerPayload=100                              #nr of transactions per payloas
txIterations=1                                 #nr of iterations of payload deliveries... all txIterations * txPerPayload = all tx being sent
txMultiBroadCast = 1                           #nr of peers to multibroadcast to
txCreateDelegates = true
txNrOfDelegates = 5
txDescription="ARK-GO Testing program running" #txDescription
dbFileName = "db/testlog.db"
singlePeerTest = true                     #if active payload will be delivered to address and port specified below
singlePeerIp = "137.74.79.171"            #deliver payload to this address
singlePeerPort = 4000                     #deliver payload to this address
autoconfigPeer = "185.170.115.40:4002"      #network autoconfigure seed peer

[account]
passphrase1="measure blue volcano month orphan only cupboard found laugh peasant drama monitor"                                  #passphrase of the test tx sending account
secondPassphrase1 =""
passphrase2="clay harbor enemy utility margin pretty hub comic piece aerobic umbrella acquire"                                  #passphrase of the test tx sending account
secondPassphrase2 =""
passphrase3="clay harbor enemy utility margin pretty hub comic piece aerobic umbrella acquire"                                  #passphrase of the test tx sending account
secondPassphrase3 =""
passphrase4="clay harbor enemy utility margin pretty hub comic piece aerobic umbrella acquire"                                  #passphrase of the test tx sending account
secondPassphrase4 =""
passphrase5="clay harbor enemy utility margin pretty hub comic piece aerobic umbrella acquire"                                  #passphrase of the test tx sending account
secondPassphrase5 =""

